# Generated by Django 4.0.6 on 2024-06-07 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthapp', '0008_myorders_qty_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.FloatField()),
                ('cat', models.IntegerField(choices=[(1, 'Personal Care'), (2, 'Health Care Devices'), (3, 'Skin Care'), (4, 'Fitness Supplement'), (5, 'Ayurvedic Care'), (6, 'Health Care')], max_length=50, verbose_name='Category')),
                ('cdetail', models.CharField(max_length=300, verbose_name='Product Detail')),
                ('cimage', models.ImageField(upload_to='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MyOrders',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='healthapp.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='healthapp.product'),
        ),
        migrations.DeleteModel(
            name='Meds',
        ),
    ]
